### ISSUE TITLE
Gridlines actually on multiples of 10?

### ISSUE THREAD

**Issue by fishbiscuit13** [cpmsmith/minimal-forecast-widget#1]
It looks like the gridlines are based on some sort of average, so like a high of 80 doesn't touch the line but 82 does. Is there a way to make sure the gridlines are actually on multiples of 10?

**Comment by cpmsmith** [comment]
Can you post an example? I'm not sure exactly what you mean. I will say, though, that the numbers on click are rounded; for instance if the highest temperature on the graph is a 79.9, it will display as 80, but won't be high enough for there to be a gridline.

**Comment by fishbiscuit13** [comment]
Sorry, I did some digging and realized it was from a size tweak I did.
