### ISSUE TITLE
Clicking on days

### ISSUE THREAD

**Issue by driesderoeck** [cpmsmith/minimal-forecast-widget#2]
I've been trying to get "Click on a day to see the high and low." working, but currently can't seem to get that done. OSX Sierra 10.12

**Comment by cpmsmith** [comment]
Are you using your selected interaction key?

![Übersicht preferences](https://cloud.githubusercontent.com/assets/9437625/19820850/3a678df4-9d29-11e6-80fa-fb28574c7f7b.png)

**Comment by driesderoeck** [comment]
I was not - thanks for pointing that out!
